// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database_interfaces

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID          string
	Title       string
	Description pgtype.Text
	Content     string
	Author      string
	Published   bool
	CreatedAt   pgtype.Timestamp
	ModifiedAt  pgtype.Timestamp
}
